'use strict';

module.exports = {
	assertCallable:   require('./assert-callable'),
	bindMethods:      require('./bind-methods'),
	clear:            require('./clear'),
	clone:            require('./clone'),
	compact:          require('./compact'),
	compare:          require('./compare'),
	copy:             require('./copy'),
	count:            require('./count'),
	descriptor:       require('./descriptor'),
	diff:             require('./diff'),
	extend:           require('./extend'),
	every:            require('./every'),
	filter:           require('./filter'),
	flatten:          require('./flatten'),
	forEach:          require('./for-each'),
	get:              require('./get'),
	getCompareBy:     require('./get-compare-by'),
	getPropertyNames: require('./get-property-names'),
	getSet:           require('./get-set'),
	isCallable:       require('./is-callable'),
	isDuplicate:      require('./is-duplicate'),
	isEmpty:          require('./is-empty'),
	isList:           require('./is-list'),
	isObject:         require('./is-object'),
	isPlainObject:    require('./is-plain-object'),
	keyOf:            require('./key-of'),
	prototype:        require('./prototype'),
	some:             require('./some')
};
