'use strict';

module.exports = {
	bindMethods:   require('./bind-methods'),
	clone:         require('./clone'),
	compact:       require('./compact'),
	count:         require('./count'),
	create:        require('./create'),
	delete:        require('./delete'),
	diff:          require('./diff'),
	elevate:       require('./elevate'),
	empty:         require('./empty'),
	every:         require('./every'),
	extend:        require('./extend'),
	filter:        require('./filter'),
	first:         require('./first'),
	forEach:       require('./for-each'),
	get:           require('./get'),
	getLength:     require('./get-length'),
	isEmpty:       require('./is-empty'),
	isPlainObject: require('./is-plain-object'),
	keyOf:         require('./key-of'),
	keysMap:       require('./keys-map'),
	link:          require('./link'),
	map:           require('./map'),
	merge:         require('./merge'),
	same:          require('./same'),
	slice:         require('./slice'),
	some:          require('./some'),
	setValue:      require('./set-value'),
	set:           require('./set'),
	toArray:       require('./to-array'),
	values:        require('./values')
};
