'use strict';

module.exports = {
	bindMethods:      require('./bind-methods'),
	clone:            require('./clone'),
	compact:          require('./compact'),
	compare:          require('./compare'),
	copy:             require('./copy'),
	count:            require('./count'),
	diff:             require('./diff'),
	empty:            require('./empty'),
	every:            require('./every'),
	extend:           require('./extend'),
	filter:           require('./filter'),
	flatten:          require('./flatten'),
	forEach:          require('./for-each'),
	get:              require('./get'),
	getPropertyNames: require('./get-property-names'),
	isDuplicate:      require('./is-duplicate'),
	isEmpty:          require('./is-empty'),
	keyOf:            require('./key-of'),
	map:              require('./map'),
	mapKeys:          require('./map-keys'),
	mapToArray:       require('./map-to-array'),
	merge:            require('./merge'),
	mergeProperties:  require('./merge-properties'),
	override:         require('./override'),
	plainCreate:      require('./plain-create'),
	plainExtend:      require('./plain-extend'),
	set:              require('./set'),
	slice:            require('./slice'),
	some:             require('./some'),
	toArray:          require('./to-array'),
	unset:            require('./unset'),
	values:           require('./values')
};
