'use strict';

module.exports = {
	bindMethods:      require('./bind-methods'),
	clone:            require('./clone'),
	compact:          require('./compact'),
	compare:          require('./compare'),
	copy:             require('./copy'),
	count:            require('./count'),
	diff:             require('./diff'),
	empty:            require('./empty'),
	every:            require('./every'),
	extend:           require('./extend'),
	filter:           require('./filter'),
	flatten:          require('./flatten'),
	forEach:          require('./for-each'),
	get:              require('./get'),
	getPropertyNames: require('./get-property-names'),
	isEmpty:          require('./is-empty'),
	isEqual:          require('./is-equal'),
	isPlainObject:    require('./is-plain-object'),
	keyOf:            require('./key-of'),
	keysMap:          require('./keys-map'),
	mapToArray:       require('./map-to-array'),
	mergeKey:         require('./merge-key'),
	mergeProperties:  require('./merge-properties'),
	override:         require('./override'),
	plainCreate:      require('./plain-create'),
	plainExtend:      require('./plain-extend'),
	unset:            require('./unset')
};
