'use strict';

module.exports = {
	binarySearch:   require('./binary-search'),
	clear:          require('./clear'),
	commonLeft:     require('./common-left'),
	compact:        require('./compact'),
	concat:         require('./concat'),
	contains:       require('./contains'),
	diff:           require('./diff'),
	eIndexOf:       require('./e-index-of'),
	eLastIndexOf:   require('./e-last-index-of'),
	exclusion:      require('./exclusion'),
	filter:         require('./filter'),
	find:           require('./find'),
	findIndex:      require('./find-index'),
	first:          require('./first'),
	firstIndex:     require('./first-index'),
	flatten:        require('./flatten'),
	forEachRight:   require('./for-each-right'),
	group:          require('./group'),
	indexesOf:      require('./indexes-of'),
	intersection:   require('./intersection'),
	isCopy:         require('./is-copy'),
	isUniq:         require('./is-uniq'),
	last:           require('./last'),
	lastIndex:      require('./last-index'),
	map:            require('./map'),
	remove:         require('./remove'),
	sepItems:       require('./sep-items'),
	slice:          require('./slice'),
	someRight:      require('./some-right'),
	splice:         require('./splice'),
	uniq:           require('./uniq')
};
